# Generated by Django 2.1.7 on 2019-02-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='default_icon.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='intro',
            field=models.TextField(default='在这里写APP介绍'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='例:抖音-用短视频记录美好生活', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='http://', max_length=100),
        ),
    ]
